import { HexagramData } from './types';

// 1 = Yang (Solid), 0 = Yin (Broken). Order: Bottom line to Top line.
// Luck ratings (general consensus from traditional fortune telling):
// 上上 (Great Fortune), 中上 (Good Fortune), 中平 (Average), 中下 (Inauspicious), 下下 (Dire/Caution)
export const HEXAGRAMS: HexagramData[] = [
  { id: 1, name: "乾", pinyin: "Qián", english: "The Creative", symbol: [1, 1, 1, 1, 1, 1], luck: "上上" },
  { id: 2, name: "坤", pinyin: "Kūn", english: "The Receptive", symbol: [0, 0, 0, 0, 0, 0], luck: "上上" },
  { id: 3, name: "屯", pinyin: "Zhūn", english: "Difficulty at the Beginning", symbol: [1, 0, 0, 0, 1, 0], luck: "下下" },
  { id: 4, name: "蒙", pinyin: "Méng", english: "Youthful Folly", symbol: [0, 1, 0, 0, 0, 1], luck: "中下" },
  { id: 5, name: "需", pinyin: "Xū", english: "Waiting", symbol: [1, 1, 1, 0, 1, 0], luck: "中上" },
  { id: 6, name: "讼", pinyin: "Sòng", english: "Conflict", symbol: [0, 1, 0, 1, 1, 1], luck: "中下" },
  { id: 7, name: "师", pinyin: "Shī", english: "The Army", symbol: [0, 1, 0, 0, 0, 0], luck: "中上" },
  { id: 8, name: "比", pinyin: "Bǐ", english: "Holding Together", symbol: [0, 0, 0, 0, 1, 0], luck: "上上" },
  { id: 9, name: "小畜", pinyin: "Xiǎo Chù", english: "The Taming Power of the Small", symbol: [1, 1, 1, 0, 1, 1], luck: "下下" },
  { id: 10, name: "履", pinyin: "Lǚ", english: "Treading", symbol: [1, 1, 0, 1, 1, 1], luck: "中上" },
  { id: 11, name: "泰", pinyin: "Tài", english: "Peace", symbol: [1, 1, 1, 0, 0, 0], luck: "上上" },
  { id: 12, name: "否", pinyin: "Pǐ", english: "Standstill", symbol: [0, 0, 0, 1, 1, 1], luck: "下下" },
  { id: 13, name: "同人", pinyin: "Tóng Rén", english: "Fellowship with Men", symbol: [1, 0, 1, 1, 1, 1], luck: "中上" },
  { id: 14, name: "大有", pinyin: "Dà Yǒu", english: "Possession in Great Measure", symbol: [1, 1, 1, 1, 0, 1], luck: "上上" },
  { id: 15, name: "谦", pinyin: "Qiān", english: "Modesty", symbol: [0, 0, 1, 0, 0, 0], luck: "中中" },
  { id: 16, name: "豫", pinyin: "Yù", english: "Enthusiasm", symbol: [0, 0, 0, 1, 0, 0], luck: "中上" },
  { id: 17, name: "随", pinyin: "Suí", english: "Following", symbol: [1, 0, 0, 1, 1, 0], luck: "中下" },
  { id: 18, name: "蛊", pinyin: "Gǔ", english: "Work on What Has Been Spoiled", symbol: [0, 1, 1, 0, 0, 1], luck: "中下" },
  { id: 19, name: "临", pinyin: "Lín", english: "Approach", symbol: [1, 1, 0, 0, 0, 0], luck: "中上" },
  { id: 20, name: "观", pinyin: "Guān", english: "Contemplation", symbol: [0, 0, 0, 0, 1, 1], luck: "中下" },
  { id: 21, name: "噬嗑", pinyin: "Shì Kè", english: "Biting Through", symbol: [1, 0, 0, 1, 0, 1], luck: "下下" },
  { id: 22, name: "贲", pinyin: "Bì", english: "Grace", symbol: [1, 0, 1, 0, 0, 1], luck: "中上" },
  { id: 23, name: "剥", pinyin: "Bō", english: "Splitting Apart", symbol: [0, 0, 0, 0, 0, 1], luck: "下下" },
  { id: 24, name: "复", pinyin: "Fù", english: "Return", symbol: [1, 0, 0, 0, 0, 0], luck: "中中" },
  { id: 25, name: "无妄", pinyin: "Wú Wàng", english: "Innocence", symbol: [1, 0, 0, 1, 1, 1], luck: "下下" },
  { id: 26, name: "大畜", pinyin: "Dà Chù", english: "The Taming Power of the Great", symbol: [1, 1, 1, 0, 0, 1], luck: "中上" },
  { id: 27, name: "颐", pinyin: "Yí", english: "Mouth Corners", symbol: [1, 0, 0, 0, 0, 1], luck: "上上" },
  { id: 28, name: "大过", pinyin: "Dà Guò", english: "Preponderance of the Great", symbol: [0, 1, 1, 1, 1, 0], luck: "中下" },
  { id: 29, name: "坎", pinyin: "Kǎn", english: "The Abysmal", symbol: [0, 1, 0, 0, 1, 0], luck: "下下" },
  { id: 30, name: "离", pinyin: "Lí", english: "The Clinging", symbol: [1, 0, 1, 1, 0, 1], luck: "中上" },
  { id: 31, name: "咸", pinyin: "Xián", english: "Influence", symbol: [0, 0, 1, 1, 1, 0], luck: "中上" },
  { id: 32, name: "恒", pinyin: "Héng", english: "Duration", symbol: [0, 1, 1, 1, 0, 0], luck: "下下" },
  { id: 33, name: "遁", pinyin: "Dùn", english: "Retreat", symbol: [0, 0, 1, 1, 1, 1], luck: "下下" },
  { id: 34, name: "大壮", pinyin: "Dà Zhuàng", english: "The Power of the Great", symbol: [1, 1, 1, 1, 0, 0], luck: "中上" },
  { id: 35, name: "晋", pinyin: "Jìn", english: "Progress", symbol: [0, 0, 0, 1, 0, 1], luck: "中上" },
  { id: 36, name: "明夷", pinyin: "Míng Yí", english: "Darkening of the Light", symbol: [1, 0, 1, 0, 0, 0], luck: "中下" },
  { id: 37, name: "家人", pinyin: "Jiā Rén", english: "The Family", symbol: [1, 0, 1, 0, 1, 1], luck: "中下" },
  { id: 38, name: "睽", pinyin: "Kuí", english: "Opposition", symbol: [1, 1, 0, 1, 0, 1], luck: "下下" },
  { id: 39, name: "蹇", pinyin: "Jiǎn", english: "Obstruction", symbol: [0, 0, 1, 0, 1, 0], luck: "下下" },
  { id: 40, name: "解", pinyin: "Xiè", english: "Deliverance", symbol: [0, 1, 0, 1, 0, 0], luck: "中上" },
  { id: 41, name: "损", pinyin: "Sǔn", english: "Decrease", symbol: [1, 1, 0, 0, 0, 1], luck: "下下" },
  { id: 42, name: "益", pinyin: "Yì", english: "Increase", symbol: [1, 0, 0, 0, 1, 1], luck: "上上" },
  { id: 43, name: "夬", pinyin: "Guài", english: "Breakthrough", symbol: [1, 1, 1, 1, 1, 0], luck: "中下" },
  { id: 44, name: "姤", pinyin: "Gòu", english: "Coming to Meet", symbol: [0, 1, 1, 1, 1, 1], luck: "中下" },
  { id: 45, name: "萃", pinyin: "Cuì", english: "Gathering Together", symbol: [0, 0, 0, 1, 1, 0], luck: "中上" },
  { id: 46, name: "升", pinyin: "Shēng", english: "Pushing Upward", symbol: [0, 1, 1, 0, 0, 0], luck: "上上" },
  { id: 47, name: "困", pinyin: "Kùn", english: "Oppression", symbol: [0, 1, 0, 1, 1, 0], luck: "中下" },
  { id: 48, name: "井", pinyin: "Jǐng", english: "The Well", symbol: [0, 1, 1, 0, 1, 0], luck: "中平" },
  { id: 49, name: "革", pinyin: "Gé", english: "Revolution", symbol: [1, 0, 1, 1, 1, 0], luck: "上上" },
  { id: 50, name: "鼎", pinyin: "Dǐng", english: "The Cauldron", symbol: [0, 1, 1, 1, 0, 1], luck: "中下" },
  { id: 51, name: "震", pinyin: "Zhèn", english: "The Arousing", symbol: [1, 0, 0, 1, 0, 0], luck: "中上" },
  { id: 52, name: "艮", pinyin: "Gèn", english: "Keeping Still", symbol: [0, 0, 1, 0, 0, 1], luck: "中下" },
  { id: 53, name: "渐", pinyin: "Jiàn", english: "Development", symbol: [0, 0, 1, 0, 1, 1], luck: "上上" },
  { id: 54, name: "归妹", pinyin: "Guī Mèi", english: "The Marrying Maiden", symbol: [1, 1, 0, 1, 0, 0], luck: "下下" },
  { id: 55, name: "丰", pinyin: "Fēng", english: "Abundance", symbol: [1, 0, 1, 1, 0, 0], luck: "中上" },
  { id: 56, name: "旅", pinyin: "Lǚ", english: "The Wanderer", symbol: [0, 0, 1, 1, 0, 1], luck: "下下" },
  { id: 57, name: "巽", pinyin: "Xùn", english: "The Gentle", symbol: [0, 1, 1, 0, 1, 1], luck: "中下" },
  { id: 58, name: "兑", pinyin: "Duì", english: "The Joyous", symbol: [1, 1, 0, 1, 1, 0], luck: "上上" },
  { id: 59, name: "涣", pinyin: "Huàn", english: "Dispersion", symbol: [0, 1, 0, 0, 1, 1], luck: "下下" },
  { id: 60, name: "节", pinyin: "Jié", english: "Limitation", symbol: [1, 1, 0, 0, 1, 0], luck: "上上" },
  { id: 61, name: "中孚", pinyin: "Zhōng Fú", english: "Inner Truth", symbol: [1, 1, 0, 0, 1, 1], luck: "下下" },
  { id: 62, name: "小过", pinyin: "Xiǎo Guò", english: "Preponderance of the Small", symbol: [0, 0, 1, 1, 0, 0], luck: "中上" },
  { id: 63, name: "既济", pinyin: "Jì Jì", english: "After Completion", symbol: [1, 0, 1, 0, 1, 0], luck: "中上" },
  { id: 64, name: "未济", pinyin: "Wèi Jì", english: "Before Completion", symbol: [0, 1, 0, 1, 0, 1], luck: "中下" }
];

export const TRIGRAMS: Record<string, { name: string; pinyin: string; nature: string; english: string }> = {
  '1,1,1': { name: '乾', pinyin: 'Qián', nature: 'Heaven', english: 'Creative' },
  '0,0,0': { name: '坤', pinyin: 'Kūn', nature: 'Earth', english: 'Receptive' },
  '1,0,0': { name: '震', pinyin: 'Zhèn', nature: 'Thunder', english: 'Arousing' },
  '0,1,0': { name: '坎', pinyin: 'Kǎn', nature: 'Water', english: 'Abysmal' },
  '0,0,1': { name: '艮', pinyin: 'Gèn', nature: 'Mountain', english: 'Still' },
  '0,1,1': { name: '巽', pinyin: 'Xùn', nature: 'Wind', english: 'Gentle' },
  '1,0,1': { name: '离', pinyin: 'Lí', nature: 'Fire', english: 'Clinging' },
  '1,1,0': { name: '兑', pinyin: 'Duì', nature: 'Lake', english: 'Joyous' },
};